### ISSUE TITLE
Stack new : should only be called once per middleware?

### ISSUE THREAD

**Issue by fzakaria** [alexedwards/stack#1]
Should Stack.New(...) only be called once per middleware chain?

I found that I had to call it a few times to provide default middleware, custom middleware and a wrapper around httprouter.

**Comment by fzakaria** [comment]
Second comment: Do you have an example of how to wrap httprouter.Handle ? I can't seem to figure it out. It was pretty straightforward with httprouter.

here is the gorilla/context version for reference:

```
func wrapHandler(next http.Handler) httprouter.Handle {
    return func(w http.ResponseWriter, r *http.Request, ps httprouter.Params) {
        context.Set("params") = ps
        next.ServeHTTP(w, r)
    }
}
```

**Comment by alexedwards** [comment]
I've fixed the second issue in the latest version. You can use the Inject function to add context during the request cycle but before the chain is executed. You can wrap httprouter.Handle like so:

``` go
func wrapHandler(hc stack.HandlerChain) httprouter.Handle {
  return func(w http.ResponseWriter, r *http.Request, ps httprouter.Params) {
    newHandlerChain := stack.Inject(hc, "params", ps)
    newHandlerChain.ServeHTTP(w, r)
  }
}
```

Full example is [in this gist](https://gist.github.com/alexedwards/4d20c505f389597c3360).
