### ISSUE TITLE
Outdated example

### ISSUE THREAD

**Issue by lopatin** [alexedwards/stack#2]
Hello, minor issue just wanted to ping you that the example for ctx.Get in the readme uses the `ok` return value which looks like it was removed [here](https://github.com/alexedwards/stack/commit/c6445b4ecd8c96092f0e422d45df6ed5a8ad7100)

Here's the readme code snippet in question:

```
func appHandler(ctx *stack.Context, w http.ResponseWriter, r *http.Request) {
  token, ok := ctx.Get("token").(string)
  if !ok {
    http.Error(w, http.StatusText(500), 500)
    return
  }
  fmt.Fprintf(w, "Token is: %s", token)
}
```

**Comment by alexedwards** [comment]
Thanks for the feedback. I think the example is correct though.

In the line `token, ok := ctx.Get("token").(string)` there's two things happening: getting the token from the context, and then type asserting it to a string using the [comma ok pattern](https://golang.org/doc/effective_go.html#interface_conversions).

The call to `ctx.Get()` returns one value - it's actually the type assertion of that value (the `.(string)` part) which returns two values.

So if you don't want to type assert the value from context you can just use:

`token := ctx.Get("token")`

If you want to type assert the value to a string immediately after getting it (like in the example) you would use:

`token, ok := ctx.Get("token").(string)`

**Comment by lopatin** [comment]
Oh interesting. Still learning Go. Thanks for the explanation.
