### ISSUE TITLE
(c *Context) copy() *Context does not properly lock the context?

### ISSUE THREAD

**Issue by achiku** [alexedwards/stack#3]
@alexedwards 

First of all, thank you for open sourcing this project! This library looks pretty nice. I'm not really familiar with go's mutex, but `(c *Context) copy() *Context` looks like it does not properly read-lock the context.

https://github.com/alexedwards/stack/blob/master/context.go#L50

``` go
func (c *Context) copy() *Context {
    nc := NewContext()
    c.mu.RLock()
    c.mu.RUnlock() // forgot to add defer?
    for k, v := range c.m {
        nc.m[k] = v
    }
    return nc
}
```

**Comment by alexedwards** [comment]
@achiku Good spot, and thanks very much for the PR. I've just merged this now.
